### ISSUE TITLE
TranslatedFieldsField expects parrent model TranslatableModel ignoring mixin

### ISSUE THREAD

**Issue by jankopacek** [django-parler/django-parler-rest#18]
in fields.py -> TranslatedFieldsField -> bind method
`if not issubclass(parent.Meta.model, TranslatableModel):
             raise TypeError("Expected 'TranslatableModel' for the parent model")`
raise Error when you use TranslatableModelMixin instead of TranslatableModel.
If I comment this out everythink is working. Could we somehow change this check?

**Comment by vdboor** [comment]
Yes, feel free to submit a pull request.

I'm curious, where are you using the mixin instead of the regular model?

**Comment by jankopacek** [comment]
I was using it for more complex inheritance, but I think it is not needed any more, because it is defined as abstract and you can override manager as well. So please close
