### ISSUE TITLE
django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy()

### ISSUE THREAD

**Issue by Ben-yeah** [django-parler/django-parler-rest#32]
Hello, The only thing I'm personally see wrong with Treebeard and Django 3.0 is that 3.0 officially deprecated ugettext_lazy, and if you run python -Wall, you'll get a ton of RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().

**Comment by ddusi** [comment]
same problem
